#include <cassert>
import std;

using namespace std;

struct pair_hash {
    std::size_t operator()(const std::pair<long long, long long>& p) const {
        auto h1 = std::hash<long long>{}(p.first);
        auto h2 = std::hash<long long>{}(p.second);
        return h1 ^ h2;
    }
};

static auto basic_problem(string_view data) {
    long long width = data.find('\n') + 1;
    long long height = data.size() / width;
    unordered_map<char, vector<pair<long long, long long>>> antennas_by_freq;
    for (const auto [i, c] : data | views::enumerate) {
        if (c != '\n' && c != '.') {
            antennas_by_freq[c].push_back(make_pair(i / width, i % width));
        }
    }
    unordered_set<pair<long long, long long>, pair_hash> antinodes;
    for (const auto& [freq, antennas] : antennas_by_freq) {
        auto sr = ranges::subrange{ antennas };
        while (!sr.empty()) {
            const auto& current = sr.front();
            auto rest = sr | views::drop(1);
            for (const auto& other : rest) {
                auto d = make_pair(current.first - other.first, current.second - other.second);
                auto ans = vector<pair<long long, long long>>{
                        make_pair(current.first + d.first, current.second + d.second),
                        make_pair(other.first - d.first, other.second - d.second)
                };
                for (const auto& an : ans) {
                    if (an.first >= 0 && an.first < height
                            && an.second >= 0 && an.second < width - 1) {
                        antinodes.insert(an);
                    }
                }
            }
            sr = rest;
        }
    }
    return antinodes.size();
}

static auto advanced_problem(string_view data) {
    long long width = data.find('\n') + 1;
    long long height = data.size() / width;
    unordered_map<char, vector<pair<long long, long long>>> antennas_by_freq;
    for (const auto [i, c] : data | views::enumerate) {
        if (c != '\n' && c != '.') {
            antennas_by_freq[c].push_back(make_pair(i / width, i % width));
        }
    }
    unordered_set<pair<long long, long long>, pair_hash> antinodes;
    string map(data);
    for (const auto& [freq, antennas] : antennas_by_freq) {
        auto sr = ranges::subrange{ antennas };
        while (!sr.empty()) {
            const auto& current = sr.front();
            auto rest = sr | views::drop(1);
            for (const auto& other : rest) {
                auto d = make_pair(current.first - other.first, current.second - other.second);
                auto cd = gcd(d.first, d.second);
                auto di = make_pair(d.first / cd, d.second / cd);
                auto an = current;
                while (an.first >= 0 && an.first < height
                        && an.second >= 0 && an.second < width - 1) {
                    antinodes.insert(an);
                    an = make_pair(an.first + di.first, an.second + di.second);
                }
                an = current;
                while (an.first >= 0 && an.first < height
                    && an.second >= 0 && an.second < width - 1) {
                    antinodes.insert(an);
                    an = make_pair(an.first - di.first, an.second - di.second);
                }
            }
            sr = rest;
        }
    }
    return antinodes.size();
}

int main() {
    auto small_vector = R"(............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
)"sv;
    auto large_vector =
        R"(.......................O......T.....d......M......
..............................F...................
..........V..................R....................
............B..t..........T..........d............
.....................B.........T................M.
..V.................................2.......M.....
.......V........................F.O..........2....
...................................T..............
..................................................
......r..........B......................c.........
.....o3.B.............................2...........
..................1...m..o....d..c.....M..........
......Qr....o............F....0............1......
....Q.......................0....................2
......t..........0................................
.............R.................................mL.
....r..............3.....................c..1.....
.........Q.........................1..............
................x...R.............................
...x........8.R...................................
..................8...............................
........x.u.................Z.....................
...........................X...............d......
....................30.....................f......
......q...............v...................c.......
..........t8.........D.3..........................
.......t.......4.............8....................
...b..................C...........D...............
.........................v..ND4..........K........
.......F.........u...........C..............fZ....
........X..9...........N.........Z..........k.....
.............X.6...q..........................k...
..............................C.Z...........m....k
...................4.v..............N.............
....................u.......D..............m......
............................vl.....UK.............
............................l..6.......f..........
..................q.4............N................
..........b....x..............fu..................
.9..................................U.......l.....
....w......b.........L......6.....z.5.............
..........X..........W6........5............z.....
...........q..........L............z........n...W.
............................5.........n...W..z....
........9........w................7....n..........
............w......................7...K.....n....
.........................U....K......W............
.........w.....L.................k....7...........
...................7.............l.............5..
..............9...................................
)"sv;
    cout << basic_problem(small_vector) << endl;
    cout << basic_problem(large_vector) << endl;
    cout << advanced_problem(small_vector) << endl;
    cout << advanced_problem(large_vector) << endl;
    return 0;
}
